<script>
  import Flashcards from "../components/Flashcards.svelte";

  const content = {
    title: `#2: Diego on muuttanut asuntoon`,

    sourcePhrases: [
      `Diego on muuttanut opiskelija-asuntoon Junatielle.`,
      `Asunto on soluasunto, jossa asuu Diegon lisäksi neljä muuta opiskelijaa.`,
      `Diego ihmettelee, miksi keittiön kaapissa on neljä erilaista jäteastiaa.`,
      `Moi Siiri, voisiks sä auttaa mua?`,
      `Mä en tiedä, mihin roskikseen nää banaaninkuoret pitää laittaa.`,
      `Joo, totta kai.`,
      `Banaaninkuoret on biojätettä.`,
      `Toi pieni vihreä astia on sitä varten.`,
      `Ahaa, okei. No mitä nää muut astiat on?`,
      `Tää iso astia on pahvipakkauksille ja toi oranssi astia on energiajätteelle.`,
      `Loput roskat on sekajätettä.`,
      `Ne voi laittaa tähän.`,
      `Mitä sekajäte oikein on?`,
      `No kaikki sellainen jäte, jota ei voi kierrättää, on sekajätettä.`,
      `Se päätyy suoraan kaatopaikalle.`,
      `Aijaa.`,
      `Tänne toiseen kaappiin me kerätään kaikki pullot ja lasipurkit.`,
      `Pullot me palautetaan kauppaan, koska niistä saa pantin.`,
      `Lasipurkit me viedään lasinkeräykseen.`,
      `Tuolla pihalla on iso jätekatos.`,
      `Kaikki jätteet voi viedä sinne.`,
      `Ohhoh, kuulostaa aika hankalalta, mut kiitti neuvoista.`,
      `Sähkölaskumme kasvaa jatkuvasti.`,
      `Vanha pakastin kuluttaa huomattavasti enemmän energiaa kuin uusi.`,
      `Olisi hyvä tarkistaa, että ikkunanne ovat tiiviit – erityisesti, jos asutte vanhassa talossa.`,
      `Toivottavasti seuraava sähkölaskunne on jo pienempi!`,
      `Vettä säästyisi, jos vähentäisitte kylpyammeessa kylpemistä ja kävisitte sen sijaan useammin suihkussa.`,
      `Tässä muutamia vinkkejä.`,
      `Teidän kannattaisi lisäksi tarkistaa kodinkoneidenne ikä.`,
      `Pesukone kannattaa käynnistää vasta kun se on täynnä.`,
      `Lopuksi vielä yksi helppo vinkki.`,
      `Haluaisitko tulla käymään meidän mökillä joskus?`,
      `Joo, tulisin tosi mielelläni!`,
      `En olisi uskonut, että Emma voittaa!`,
      `Etkö? Hän olisi voinut voittaa jo viime vuonna, jos olisi osallistunut.`,
      `Menisitkö uimaan, jos vesi olisi lämmintä?`,
      `Jos voittaisin lotossa, matkustaisin Australiaan.`,
      `Ottaisin kupin kahvia.`,
      `Sanoisitko nimesi?`,
      `Menisimmekö lomalla Portugaliin?`,
      `Olisipa jo loma!`,
      `Kunpa huomenna ei sataisi!`,
      `Gepardi on nopea eläin.`,
      `Gepardi juoksee nopeasti.`,
      `Anna on kaunis.`,
      `Anna laulaa kauniisti.`,
      `Joku voisi ajatella, että ympäristöystävällisesti eläminen on hankalaa ja aikaa vievää.`,
      `Näin ei kuitenkaan ole!`,
      `Tässä joitakin vinkkejä, joilla voit helposti aloittaa uuden kestävän elämäntavan.`,
      `Voit aloittaa vähentämällä mainospostia.`,
    ],

    targetPhrases: [
      `Diego has moved into a student apartment on Junatie.`,
      `The apartment is a cell apartment where four other students live in addition to Diego.`,
      `Diego is wondering why there are four different bins in the kitchen cabinet.`,
      `Hi Siiri, can you help me?`,
      `I don't know which bin to put the banana peels in.`,
      `Yes of course.`,
      `Banana peels are biowaste.`,
      `That little green container is for that.`,
      `Ahaa, okay. Well what are these other dishes?`,
      `This big container is for cardboard packaging and that orange container is for energy waste.`,
      `The rest of the rubbish is mixed waste.`,
      `They can be put here.`,
      `What exactly is mixed waste?`,
      `Well, all the kind of waste that can’t be recycled is mixed waste.`,
      `It ends up in landfill.`,
      `Oh right.`,
      `We collect all the bottles and glass jars in this other cupboard.`,
      `We return the bottles to the shop, because they get a deposit.`,
      `We take the glass jars to the glass recycling.`,
      `There is a big trash container in that yard.`,
      `All the waste can be taken there.`,
      `Oho, sounds quite awkward, but thanks for the tips.`,
      `Our electricity bill is constantly growing.`,
      `An old freezer consumes significantly more energy than a new one.`,
      `It would be good to check if your windows are sealed – especially if you live in an old house.`,
      `Hopefully your next electricity bill will already be smaller!`,
      `You would save water if you bathed less in the bathtub and took a shower more often instead.`,
      `Here are a few tips.`,
      `You should also check the age of your appliances.`,
      `The washing machine should only be started when it is full.`,
      `Finally, one more easy tip.`,
      `Would you like to come to our summer cottage sometime?`,
      `Yeah, I'd love to come!`,
      `I wouldn't have thought Emma would win!`,
      `Don't you? She could have won last year if she had participated.`,
      `Would you go swimming if the water was warm?`,
      `If I won the lottery, I would travel to Australia.`,
      `I'd like a cup of coffee.`,
      `Would you say your name?`,
      `Would we go on holiday to Portugal?`,
      `Have a vacation already!`,
      `I wish it wouldn't rain tomorrow!`,
      `The cheetah is a fast animal.`,
      `The cheetah runs fast.`,
      `Anna is beautiful.`,
      `Anna sings beautifully.`,
      `One might think that living in an environmentally friendly way is difficult and time consuming.`,
      `However, this is not the case!`,
      `Here are some tips to help you easily start a new sustainable lifestyle.`,
      `To get started, reduce your promotional mail.`,
    ],
  };
</script>

<Flashcards {...content} />
