<script>
  import Flashcards from "../components/Flashcards.svelte";

  const content = {
    title: `#P1: Päätimme eilen lähteä...`,

    targetPhrases: [
      `Päätimme eilen lähteä työkavereiden kanssa ulos syömään.`,
      `Minä suosittelin uutta ravintola Koloa, koska olin käynyt siellä kerran lounaalla ja ruoka oli ollut edullista ja tarjoilijat ystävällisiä.`,
      `Pidin myös paikan ajattomasta sisustuksesta ja kiireettömästä tunnelmasta.`,
      `Mutta mikä pettymys!`,
      `Meitä odottivat mauttomat annokset ja ilmeetön tarjoilija.`,
      `Valkoiset kankaiset lautasliinat olivat vaihtuneet paperisiin ruudullisiin.`,
      `Ruokalistalla ei tietenkään ollut yhtään laktoositonta annosta ja kaiken lisäksi juomatkin olivat lämpimiä.`,
      `Tästä onnettomasta palvelusta emme halunneet maksaa yhtään ylimääräistä, joten kahvit joimme toisessa kahvilassa ihanista kukallisista kahvikupeista.`,
      `Tänään on lämmin ilma.`,
      `Aurinko paistaa lämpimästi.`,
      `Tämä pesukone oli edullinen.`,
      `Ostin sen edullisesti naapureiltani.`,
      `Sadun asunto on kodikas.`,
      `Hän on sisustanut sen kodikkaasti.`,
      `Ystäväni on surullinen.`,
      `Hän katsoo minua surullisesti.`,
      `Isoäitini on aina iloinen.`,
      `Hän hymyilee kaikille iloisesti.`,
      `Isoisälläni on huono kuulo.`,
      `Hän kuulee huonosti.`,
      `Kalle syö vain terveellistä ruokaa.`,
      `Hän elää muutenkin terveellisesti.`,
      `Tämä tehtävä oli helppo.`,
      `Tein tehtävän helposti.`,
      `Asut aseman vieressä.`,
      `Matkustatko töihin junalla vai autolla?`,
      `Kumpaa pesuainetta ostat: edullista ja epäekologista vai ympäristöystävällistä mutta kallista?`,
      `Mene yksi askel eteenpäin!`,
      `Jos haet työpaikan kahvilasta kahvia mukaan, otatko kahvin pahvimukiin vai onko sinulla oma muki mukana?`,
      `Kun käyt suihkussa, suljetko vesihanan, kun peset hiuksesi?`,
      `Kuinka lämmin sisäilma kotonasi on?`,
      `Sammutatko aina valot huoneesta, kun lähdet sieltä pois?`,
      `Kuinka kauan olet yleensä suihkussa?`,
      `Pesetkö astiat juoksevan veden alla?`,
      `Jos ajat autoa, onko ajotyylisi rauhallinen vai painatko usein kaasua ja jarrua?`,
      `Ostatko vaatteita tai tavaroita kirpputorilta?`,
      `Vietkö vanhat vaatteet kierrätykseen vai heitätkö ne roskiin?`,
      `Ostatko reilun kaupan banaaneja vai tavallisia banaaneja?`,
      `Vietkö paristot kierrätykseen?`,
      `Ostatko käytettyjä huonekaluja tai urheiluvälineitä?`,
      `Sammutatko tietokoneen illalla?`,
      `Otatko puhelimen laturin irti seinästä, kun akku on täynnä?`,
      `Kuivaatko pyykit kuivausrummussa vai ripustatko ne kuivumaan narulle?`,
      `Matkustatko työmatkat yksin autolla?`,
      `Ovatko astianpesukone ja pesukone aina täynnä, kun laitat ne päälle?`,
      `Heitätkö ruokaa roskiin?`,
      `Mitä teet tyhjille pulloille?`,
      `Jos matkustaisit Lappiin, menisitkö junalla vai lentokoneella, jos liput maksaisivat yhtä paljon?`,
      `Annatko rahaa ympäristönsuojeluorganisaatioille?`,
      `Ostatko luomuruokaa?`,
    ],

    sourcePhrases: [
      `We decided yesterday to go out with some work mates to eat.`,
      `I recommended the new restaurant Koloa because I had visited there once for lunch and the food had been affordable and the waiters friendly.`,
      `I also liked the timeless decor and unhurried atmosphere of the place.`,
      `But what a disappointment!`,
      `A tasteless portion and an expressionless waiter were waiting for us.`,
      `The white cloth napkins had changed to paper plaids.`,
      `Of course, there were no lactose-free portions on the menu and, on top of all that, the drinks were warm.`,
      `We didn’t want to pay any extra for this unfortunate service, so we drank coffee in another cafe from lovely flowery coffee cups.`,
      `Today is warm.`,
      `The sun is shining warmly.`,
      `This washing machine was affordable.`,
      `I bought it cheaply from my neighbors.`,
      `The fairytale apartment is cozy.`,
      `He has decorated it cosily.`,
      `My friend is sad.`,
      `He is looking at me sadly.`,
      `My grandmother is always happy.`,
      `She smiles happily at everyone.`,
      `My grandfather has poor hearing.`,
      `He hears badly.`,
      `Kalle only eats healthy food.`,
      `He lives a healthy life anyway.`,
      `This task was easy.`,
      `I did the task easily.`,
      `You live next to the station.`,
      `Do you travel to work by train or car?`,
      `Which detergent do you buy: cheap and unecological or environmentally friendly but expensive?`,
      `Take it one step further!`,
      `If you are getting coffee from a coffee shop, do you take the coffee in a cardboard mug or do you have your own mug with you?`,
      `When you take a shower, do you turn off the water tap when you wash your hair?`,
      `How warm is the indoor air in your home?`,
      `Do you always turn off the lights in the room when you leave?`,
      `How long are you usually in the shower?`,
      `Do you wash the dishes under running water?`,
      `If you drive a car, is your driving style calm or do you often apply the accelerator and brake?`,
      `Do you buy clothes or goods from the flea market?`,
      `Do you take old clothes for recycling or do you throw them in the trash?`,
      `Do you buy fair trade bananas or plain bananas?`,
      `Do you recycle batteries?`,
      `Do you buy used furniture or sports equipment?`,
      `Do you turn off your computer in the evening?`,
      `Do you unplug the phone charger when the battery is full?`,
      `Do the clothes dry in the dryer or do they hang to dry on a string?`,
      `Do you travel alone by car?`,
      `Are the dishwasher and washing machine always full when you turn them on?`,
      `Do you throw food in the trash?`,
      `What do you do with empty bottles?`,
      `If you traveled to Lapland, would you go by train or plane if the tickets cost the same?`,
      `Do you give money to environmental organisations?`,
      `Do you buy organic food?`, 
    ],
  };
</script>

<Flashcards {...content} />
